# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Courses
    weight: 20
    identifier: courses
  - name: DDLS 2024
    PageRef: course/ddls-2024/_index.md
    weight: 5
    parent: courses
  - name: DDLS 2023
    PageRef: course/ddls-2023/_index.md
    weight: 10
    parent: courses
  - name: DDLS 2022
    PageRef: course/ddls-2022/_index.md
    weight: 20
    parent: courses
  - name: Announcements
    PageRef: post/_index.md
    weight: 30
  - name: Contact
    PageRef: contact/index.md
    weight: 60
